### PR TITLE
Extend definition of Directors of Operations and add Santi as a DoO

### PR DESCRIPTION
**Pull request by lheagy**
Add Santiago Soler (@santisoler) as a co-director of operations for SimPEG. 

Santi's contributions to SimPEG include improving documentation of code (e.g. simpeg/simpeg#1192) and for the community (e.g. simpeg/simpeg#1247), code quality (simpeg/simpeg#1200, simpeg/simpeg#1202, simpeg/simpeg#1238 are just a few!), refactoring and improving the clarity of code (e.g. simpeg/simpeg#1241), adding features to improve interoperability with fatiando and other communities (e.g. simpeg/discretize#325). He is leading the BIRS 2023 workshop and playing an important role in supporting the community. 

I would like to nominate Santi as a co-director of operations for SimPEG and to give him administrative access to SimPEG on github. I have chatted with both @santisoler and @jcapriot about adding Santi as an admin to the SimPEG org, and I would like to use this pr to formalize this. 

@rowanc1, @sgkang, @jcapriot and @santisoler: could you please indicate if you support adding Santi as an admin and co-director of operations for SimPEG with a 👍 and / or comment below? If you have any questions or concerns, please feel free to reach out to me. I would be happy to chat.

### CODE REVIEW

**Review by rowanc1 — APPROVED** [review]
Love it. Thanks for all your help @santisoler! 🚀

**Comment by sgkang** [comment]
I am so glad to hear @santisoler is stepping up and playing an important role for the SimPEG community. 
Two thumbs up for including @santisoler as a co-director of SimPEG!

**Review by sgkang — APPROVED** [review]
I am so glad to hear @santisoler is stepping up and playing an important role for the SimPEG community.
Two thumbs up for including @santisoler as a co-director of SimPEG!

**Comment by santisoler** [comment]
Thanks @lheagy for the offering, and @jcapriot, @sgkang, @rowanc1 for accepting me. I gladly accept this role!

**Review by santisoler — APPROVED** [review]

**Comment by santisoler** [comment]
Is this ready to be merged? Are there any changes to be made?

**Comment by jcapriot** [comment]
I'd like to see a better distinction in duties personally. Just to be transparent, when Lindsey and I originally discussed this we had talked only about adding you as an administrator for simpeg.

We had wanted to discuss how the running of simpeg should work in the future and if the current model needs updating when multiple people from multiple organizations have a role (e.g. do we move to a steering council type approach?)

**Comment by lheagy** [comment]
Thanks so much to @jcapriot, @santisoler, @rowanc1 and @sgkang for the constructive conversations about making some updates to our governance structure. I will respond here in light of the comments above and then create a couple of pr’s (to follow soon!).  

First, with respect to the title of “Director of Operations”: this title was when Joe came to UBC GIF. This role combined technical leadership in SimPEG with the deliverables and needs of the GIF research group. But now, we have expanded in the folks who are contributing to core maintenance (thrilled to have Santi’s leadership in SimPEG too🚀), and we have core maintainers at multiple institutions, so having a singular title doesn’t work. Also, the “Director” naming mixes a title that describes responsibilities with a way to give attribution and acknowledgement of contributions in SimPEG. To update the role descriptions, here is the plan: 

Retire the title of “Director of Operations.” The role of **Maintainer** replaces the Director of Operations role and focuses the scope to SimPEG and the responsibilities of a Maintainer. In the upcomig pr, we will outline the responsibilities of being a Maintainer and GitHub Admin in the SimPEG organization. This is the group of people with the ability to merge PRs, and have access on conda-forge, pip, etc (We can use the PR to flesh out the Maintainer description). Currently, @jcapriot and @santisoler are Maintainers of SimPEG. They both have admin permissions in the project. 

Next, we should explore creating a SimPEG Distinguished Contributors award: this can be an avenue to acknowledge long-standing contributions to the project and is something that people can put on their CVs. This is where we attribute and celebrate contributions. To initiate this discussion, I will start a separate PR with suggestions for how we set this up and ask for input from the community on how we nominate contributors as well as bootstrap this for the first year. I think an important piece will be to include a citation (much like other awards) so that we can describe the contributions. This is loosely modelled after the [Jupyter community](https://jupyter.org/governance/distinguished_contributors.html). 

The current model then falls back to a BDFL style in all but name. Few other open-source projects use the “Managing Director” title (and “Director” in both cases feels a bit corporate for an open-source project). We will also remove the “Managing Director” title to align this with other open-source communities and stick with BDFL.  

Overall, this is primarily a renaming of the existing roles in the project, and better identifying contributions and responsibilities. Strategic decision-making happens as we do it now – over PRs and in SimPEG meetings. With the formalization of an admin role, we aim to increase the capacity of our community and continue to improve and solicit contributions. Over the coming years, we can consider a steering council approach, especially as more lab groups are formally and financially dependent on SimPEG. However, the project funding base is primarily from a single institution at the moment, so continuing with a BDFL model for the time being keeps the governance and formality lightweight. Ideally, governance should be a structure that is there in the background, but there when we need it. Decisions are first and foremost made with the community. To help promote opportunities for strategic thinking about the project and community, I will start one more pr where we can add a document that helps us track and initiate semi-regular meetings dedicated to strategic thinking.

I am excited about the steps we are taking here as the project and community continue to grow!

**Comment by santisoler** [comment]
Shall we close this PR in favor of #18 then?

**Comment by lheagy** [comment]
closing in favour of #18

**Pull request closed without merging**
