### PR TITLE
Update governance.md

### PR DESCRIPTION
**Pull request by sgkang**
@lheagy: Looks good to me, and it is nice to have a formal document about the governance.

### CODE REVIEW

**Comment by lheagy** [comment]
Thanks for starting this @sgkang! For process, I suggest that folks submit reviews / suggestions as a pull request review. If you are happy with it as is, you can "accept" the review. 

Is two weeks enough time for folks to provide input? We can tentatively plan to merge on May 12 if there are no out-standing comments at that point

**Review by prisae — APPROVED** [review]
LGTM, thanks for pushing on this Lindsey!

**Comment by micmitch** [comment]
Looks like a good governance framework to me!

**Review by jcapriot — APPROVED** [review]
This has been looking great!

**Pull request merged**
